package com.mycompany.mavenproject2.View.Telas;

import com.mycompany.mavenproject2.Servicos.ClasseProcessadora;
import com.mycompany.mavenproject2.Constantes;
import com.mycompany.mavenproject2.Servicos.CriadorDeArquivoPython;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Emanuel
 */
public class TelaTexto extends javax.swing.JFrame {
    
    private int modo;
    /**
     * Creates new form TelaTexto
     */
    
    public TelaTexto(int modo) {
        initComponents();
        this.modo = modo;
        if(modo==3){
          this.setVisible(true);
        }else{
          this.carregarCampoDeTextoDeCodigo();     
        }
        
    }
    public static void lançarTelaTexto(JFrame tela, int modo){
        tela.dispose();
        TelaTexto telaInicial= new TelaTexto(modo); 
        telaInicial.setVisible(true);
    }    
    
    private String retornarTextoComOErroGerado(String codigoPythonSemErroIntencional){
        CriadorDeArquivoPython.gravar("codigoPythonSemErroIntencional.py",codigoPythonSemErroIntencional);
        String codigoPythonComErroIntencional = ClasseProcessadora.setarComando("introduzerrofor.py","codigoPythonSemErroIntencional.py");
        return codigoPythonComErroIntencional;
    }
    
    
    public void carregarCampoDeTextoDeCodigo(){
        String resultadoDaExecucaoTesseract = ClasseProcessadora.setarComando("teste04.py", Constantes.NOME_DA_IMAGEM_GERADA);;
        if(modo == Constantes.MODO_OCR_COM_INSERCAO_DE_ERROS){
            resultadoDaExecucaoTesseract = retornarTextoComOErroGerado(resultadoDaExecucaoTesseract);
        }
        
        this.codigoPythonTextArea.setText(resultadoDaExecucaoTesseract);
        
    }
    
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        codigoPythonTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadoDaExecucaoTextArea = new javax.swing.JTextArea();
        executarProgramaButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoPythonTextArea.setColumns(20);
        codigoPythonTextArea.setRows(5);
        jScrollPane1.setViewportView(codigoPythonTextArea);

        resultadoDaExecucaoTextArea.setColumns(20);
        resultadoDaExecucaoTextArea.setRows(5);
        jScrollPane2.setViewportView(resultadoDaExecucaoTextArea);

        executarProgramaButton.setText("Executar Programa");
        executarProgramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarProgramaButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar Tela Inicial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(executarProgramaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executarProgramaButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void compilarCodigoPython(String nomedoArquivo){
        resultadoDaExecucaoTextArea.setText("");
        String conteudo=codigoPythonTextArea.getText();
        CriadorDeArquivoPython.gravar(nomedoArquivo,conteudo);
        String resultadoDaExecucaoDoCodigoPython = ClasseProcessadora.setarComandoRoda(nomedoArquivo);
        if(resultadoDaExecucaoDoCodigoPython.equals("")){
            resultadoDaExecucaoTextArea.setText("ERRO DE COMPILAÇÃO");
        }
        else{
            resultadoDaExecucaoTextArea.setText(resultadoDaExecucaoDoCodigoPython);
        }
    }  
    
    private void executarProgramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarProgramaButtonActionPerformed
        compilarCodigoPython("CodigoPythonGerado.py");
        //introduzerro("programaerro3");
    }//GEN-LAST:event_executarProgramaButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaDeDisparo.lançarTelaDeDisparo(this);
    }//GEN-LAST:event_jButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea codigoPythonTextArea;
    private javax.swing.JButton executarProgramaButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultadoDaExecucaoTextArea;
    // End of variables declaration//GEN-END:variables
}
