/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2.View.Telas;

import com.mycompany.mavenproject2.Constantes;
import com.mycompany.mavenproject2.View.MouseTracker;
import javax.swing.JFrame;

/**
 *
 * @author Emanuel
 */
public class TelaDeDisparo extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeDisparo
     */
    public TelaDeDisparo() {
        initComponents();
    }
    public static void lançarTelaDeDisparo(JFrame tela){
        tela.dispose();
        TelaDeDisparo telaInicial= new TelaDeDisparo(); 
        telaInicial.setVisible(true);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispararOCRButton = new javax.swing.JButton();
        dispararOCRComInsercaoDeErrosButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispararOCRButton.setText("Disparar OCR");
        dispararOCRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispararOCRButtonActionPerformed(evt);
            }
        });

        dispararOCRComInsercaoDeErrosButton.setText("Disparar OCR com Inserção de Erros");
        dispararOCRComInsercaoDeErrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispararOCRComInsercaoDeErrosButtonActionPerformed(evt);
            }
        });

        tituloLabel.setText("APRENDENDO PYTHON COM OCR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dispararOCRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dispararOCRComInsercaoDeErrosButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(dispararOCRButton)
                .addGap(61, 61, 61)
                .addComponent(dispararOCRComInsercaoDeErrosButton)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lancarMouseTrackerDadoModo(int modo){
        MouseTracker mouseTracker = new MouseTracker();
        mouseTracker.start(modo);
        this.dispose();
        
    }
    
    private void dispararOCRComInsercaoDeErrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispararOCRComInsercaoDeErrosButtonActionPerformed
        lancarMouseTrackerDadoModo(Constantes.MODO_OCR_COM_INSERCAO_DE_ERROS);
    }//GEN-LAST:event_dispararOCRComInsercaoDeErrosButtonActionPerformed

    private void dispararOCRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispararOCRButtonActionPerformed
        lancarMouseTrackerDadoModo(Constantes.MODO_OCR);
    }//GEN-LAST:event_dispararOCRButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dispararOCRButton;
    private javax.swing.JButton dispararOCRComInsercaoDeErrosButton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
